[project]
name = "slackbolt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-decouple>=3.8",
    "requests>=2.32.4",
    "slack-bolt>=1.23.0",
]
